# Generated by Django 4.2.1 on 2025-04-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='client',
            field=models.CharField(max_length=255),
        ),
    ]
